Update README.md
mucinoab/Covid pull request #100
Opened 2021-02-04 21:38 UTC by mucinoab

Arregla html.

2021-02-04 21:39 UTC, mucinoab commented
Vean [el actual.](https://github.com/mucinoab/Reporstat)

2021-02-04 22:24 UTC, dianapg8 approved these changes

2021-02-04 22:25 UTC, dianapg8 commented
![image](https://user-images.githubusercontent.com/60493134/106963021-98bdb900-6705-11eb-9998-6188a0634ce9.png)
algo falta no??

2021-02-04 22:27 UTC, dianapg8 requested changes
Aparece código sin sentido

2021-02-04 22:47 UTC, yollotltamayo approved these changes

2021-02-04 22:49 UTC, mucinoab commented
> Aparece código sin sentido

Es HTML, el PR lo arregla.

2021-02-04 22:50 UTC, Lara272 approved these changes

2021-02-05 00:03 UTC, Gabrielagogo approved these changes

2021-02-05 00:04 UTC, dianapg8 approved these changes

2021-02-05 00:04 UTC, merged