cambio_funcion_unir
mucinoab/Covid pull request #28
Opened 2021-01-21 03:22 UTC by Gabrielagogo

se realizo el cambio del simbolo señalado y se documento

2021-01-21 03:51 UTC, Lara272 approved these changes

2021-01-21 04:56 UTC, Diana-LR submitted a review, later dismissed

2021-01-21 05:24 UTC, yollotltamayo commented on src/Operations.jl
> +q1 = DataFrame(ID = [10,20,30,40], Nombre = ["gaby", "erandi","rosa","jose"])
Esta forma de documentar no va a funcionar , checa los ejemplos en otros codigos para que veas como funciona.

2021-01-21 05:28 UTC, yollotltamayo requested changes
Si tienes duda preguntanos Gaby, el codigo que pasaste no une nada.

2021-01-21 05:28 UTC, yollotltamayo commented on src/Operations.jl
> +
Esto no funciona, en ningun momento esta uniendo la nueva tabla

2021-01-21 20:46 UTC, Lara272 approved these changes

2021-01-22 18:25 UTC, dianapg8 approved these changes

2021-01-30 03:29 UTC, closed without merging