Homologando funciones
mucinoab/Covid pull request #66
Opened 2021-01-31 06:33 UTC by dianapg8

data_check() es ahora cargar_csv
CSV_to_DataFrame es ahora csv_a_DataFrame
poblacion_todos_entidades() es ahora poblacion_todas_entidades
sumafila() es ahora sumar_fila()
sumacolumna() es ahora sumar_columna()

2021-01-31 19:42 UTC, mucinoab requested changes

2021-01-31 19:42 UTC, mucinoab commented on src/Operations.jl
> +export seleccionar, filtrar, contar_renglones, unzip, cargar_csv, fechahoy, sumacolumna, sumafila,CSV_to_DataFrame, jsonparse
Faltó cambiar aca ¿No?

2021-01-31 23:54 UTC, dianapg8 commented on src/Operations.jl
> +export seleccionar, filtrar, contar_renglones, unzip, cargar_csv, fechahoy, sumacolumna, sumafila,CSV_to_DataFrame, jsonparse
Listo

2021-01-31 23:56 UTC, mucinoab approved these changes

2021-01-31 23:57 UTC, mucinoab requested changes
¿Cambiaste los tests?

2021-01-31 23:59 UTC, dianapg8 commented
O.o segun yo no
@yollotltamayo me ayudo con lo de las dependencias no se si tenga que ver eso

2021-02-01 00:01 UTC, mucinoab commented
> O.o segun yo no
> @yollotltamayo me ayudo con lo de las dependencias no se si tenga que ver eso

Me refiero a que en los tests necesitas cambiar de igual manera el nombre de las funciones. 
Prueba que funcionen con: 
`julia --project test/runtests.jl`

2021-02-01 00:31 UTC, dianapg8 commented
> > O.o segun yo no
> > @yollotltamayo me ayudo con lo de las dependencias no se si tenga que ver eso
> 
> Me refiero a que en los tests necesitas cambiar de igual manera el nombre de las funciones.
> Prueba que funcionen con:
> `julia --project test/runtests.jl`

listo

2021-02-01 02:07 UTC, mucinoab approved these changes

2021-02-01 16:33 UTC, yollotltamayo approved these changes

2021-02-01 16:34 UTC, merged